

export const metadata = {
    title: 'View Detail Blog',
    description: 'Generated by create next app',
  }
  
  export default function ViewDetailLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <>
     {children}
     </>
         
    )
  }
  